name: build

permissions:
  contents: write
  packages: read

on:
  push:
    branches:
    - main
  workflow_dispatch:
  workflow_call:

jobs:
  build_windows:
    strategy:
      matrix:
        arch: ["amd64"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: "./.github/actions/build-windows"
      with:
        GOARCH: ${{ matrix.arch }}
