name: release

permissions:
  contents: write
  packages: read

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: "./.github/workflows/build.yml"

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: List artifacts
        shell: bash
        run: ls -la artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}