name: release

permissions:
  contents: write
  packages: read

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build-and-release:
    uses: "./.github/workflows/build.yml"
    with:
      release-url: ${{ create-release.outputs.upload_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
